name: ci
on:
  release:
    types: [published]
  push:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        node-version: ["16.17.0", "18.9.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release name
        id: tag
        run: |
          # Default GITHUB_SHA
          tag="${GITHUB_SHA}"

          # If release parse the tag name from GITHUB_REF
          if [ "${GITHUB_EVENT_NAME}" == "release" ]; then
            ref="${GITHUB_REF}"
            tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
          fi

          echo "::set-output name=tag::$tag"
      # setup docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # setup node
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # setup pnpm
      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      # build app
      - run: pnpm i
      - run: pnpm build
      # build docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: NODE_VERSION=${{ matrix.node-version }}
          tags: |
            ghcr.io/schizofreny/node-otel:${{ matrix.node-version }}-${{ steps.tag.outputs.tag }}
